baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'S/V Specialissima'
theme = "hugo-bootstrap-theme"
themesdir = "node_modules/@filipecarneiro"

[params]
favicon = "/assets/images/logo.png"
#sectionPagesMenu = "main"

