[[main]]
name = "Spec"
url = "spec"
weight = 20
title = "SV Specialissima"

[[main]]
identifier = "blog"
name = "Blog"
weight = 40

[[main]]
name = "All"
url = "post"
weight = 100
parent = "blog"

[[main]]
name = "Prepearation"
url = "tags/prep"
weight = 20
parent = "blog"

[[main]]
name = "Ideas"
url = "tags/ideas"
weight = 30
parent = "blog"

[[main]]
identifier = "docs"
name = "Docs"
url = "page"
weight = 50

[[main]]
identifier = "crews"
name = "Crews"
url = "crews"
weight = 60

[[main]]
identifier = "kids-corner"
name = "Kids Corner"
url = "kids-corner"
weight = 70

[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/hugo-bootstrap-theme/images/feather/feather-sprite.svg#github'/></svg>"
  url = "https://github.com/filipecarneiro/hugo-bootstrap-theme/"
  weight = 10
  title = "Visit the GitHub project"

[[social]]
  name = "Twitter"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='/hugo-bootstrap-theme/images/feather/feather-sprite.svg#twitter'/></svg>"
  url = "https://twitter.com/jfilipecarneiro/"
  weight = 20
  title = "Contact on Twitter"
